export const FETCH_ADVERTISEMENTS = 'FETCH_ADVERTISEMENTS'
export const FETCH_ADVERTISEMENTS_COMPLETED = 'FETCH_ADVERTISEMENTS_COMPLETED'

export const FETCH_BOOK_LANDING = 'FETCH_BOOK_LANDING'
export const FETCH_BOOK_LANDING_COMPLETED = 'FETCH_BOOK_LANDING_COMPLETED'

export const FETCH_BOOK_DETAIL = 'FETCH_BOOK_DETAIL'
export const FETCH_BOOK_DETAIL_COMPLETED = 'FETCH_BOOK_DETAIL_COMPLETED'

export const FETCH_CHAPTER = 'FETCH_CHAPTER';
export const FETCH_CHAPTER_COMPLETE = 'FETCH_CHAPTER_COMPLETE';

export const FETCH_BOOK_BASE_CATEGORY = 'FETCH_BOOK_BASE_CATEGORY';
export const FETCH_BOOK_BASE_CATEGORY_COMPLETED = 'FETCH_BOOK_BASE_CATEGORY_COMPLETED';

export const FETCH_TAGS = 'FETCH_TAGS';
export const FETCH_TAGS_COMPLETE = 'FETCH_TAGS_COMPLETE';

export const FETCH_SEARCH_BOOKS = 'FETCH_SEARCH_BOOKS';
export const FETCH_SEARCH_BOOKS_COMPLETE = 'FETCH_SEARCH_BOOKS_COMPLETE';


export const BLOCK_UI = 'BLOCK_UI';
export const UNBLOCK_UI = 'UNBLOCK_UI';